language: node_js
node_js:
  - "4.4"
script:
  - "npm test"
after_success:
  - "npm run coveralls"
  - cat ./coverage/lcov.info ./coverage/karma/**/*.info > lcov.info
  - node node_modules/lcov-filter/index.js lcov.info config | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
