language: node_js
node_js:
  - "4.4"
notifications:
  email: false
script:
  - "npm test"
after_success:
  - "istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
